@ECHO OFF
DEL BELLONA2.ARJ
DEL *.BIN
CALL SWEEP.BAT .
CALL SWEEP.BAT VFS
CALL SWEEP.BAT W32DIO
CALL SWEEP.BAT LOADER
CALL SWEEP.BAT JSHELL
CALL SWEEP.BAT BELLDISK
CALL SWEEP.BAT BELL_FS
CALL SWEEP.BAT CALCSTR
CALL SWEEP.BAT LINENUM
CALL SWEEP.BAT W32DIO\HDDREAD
CALL SWEEP.BAT COFFDBG
CALL SWEEP.BAT COFFDBG2
CALL SWEEP.BAT MODULE\KERNELB
CALL SWEEP.BAT CODEMAP
CALL SWEEP.BAT V86LIB

ARJ A  BELLONA2
ARJ A  BELLONA2 BLOAD
ARJ A  BELLONA2 LINENUM
ARJ A  BELLONA2 LOADER
ARJ A  BELLONA2 COFFDBG
ARJ A  BELLONA2 COFFDBG2
ARJ A  BELLONA2 CALCSTR
ARJ A  BELLONA2 VFS
ARJ A  BELLONA2 CALCSTR
ARJ A  BELLONA2 BELLDISK
ARJ A  BELLONA2 BOOTSECT
ARJ A  BELLONA2 BCMOS
ARJ A  BELLONA2 PELOAD
ARJ A  BELLONA2 W32DIO
ARJ A  BELLONA2 JSHELL
ARJ A  BELLONA2 W32IORJJ
ARJ A  BELLONA2 BELL_FS
ARJ A  BELLONA2 MODULE
ARJ A  BELLONA2 CODEMAP
ARJ A  BELLONA2 V86LIB
ARJ A  BELLONA2 MODULE\KERNELB
ARJ A  BELLONA2 W32DIO\HDDREAD
ARJ A  BELLONA2 DISK\RAWRITE.EXE

