name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
        
    - name: MKDIR
      run: |
        mkdir lib
        mkdir disk
        mkdir cod
        copy missing/jpeg.lib lib
        copy missing/wall.bmp disk
        copy missing/jpeg.mod disk
        copy missing/hdd.img disk
        copy missing/qemu-img.exe disk
        copy missing/libssp-0.dll disk
        copy missing/libzstd-1.dll disk
        copy bload/bload.com disk
        copy bootsect/boot.bin disk
        

    - name: codemap
      working-directory: ${{env.GITHUB_WORKSPACE}}codemap      
      run: msbuild codemap.sln /t:Build /p:Configuration=Debug /p:Platform=Win32
      
    - name: belldisk
      working-directory: ${{env.GITHUB_WORKSPACE}}belldisk      
      run: msbuild belldisk.sln /t:Build /p:Configuration=Debug /p:Platform=x86
      
    - name: stubv86
      working-directory: ${{env.GITHUB_WORKSPACE}}stubv86      
      run: msbuild stubv86.sln /t:Build /p:Configuration=Release /p:Platform=Win32
      
    - name: bell_fs
      working-directory: ${{env.GITHUB_WORKSPACE}}bell_fs      
      run: msbuild bell_fs.sln /t:Build /p:Configuration=Debug /p:Platform=Win32 
      
    - name: imagetool
      working-directory: ${{env.GITHUB_WORKSPACE}}imagetool
      run: msbuild imagetool.sln /t:Build /p:Configuration=Debug /p:Platform=x86
      
    - name: bellona2
      working-directory: ${{env.GITHUB_WORKSPACE}}kernel
      run: msbuild bellona2.sln /t:Build /p:Configuration=Debug /p:Platform=x86   
      
    - name: startup
      working-directory: ${{env.GITHUB_WORKSPACE}}module/startup      
      run: msbuild startup.sln /t:Build /p:Configuration=Debug /p:Platform=Win32 

    - name: stdlib
      working-directory: ${{env.GITHUB_WORKSPACE}}module/stdlib      
      run: msbuild stdlib.sln /t:Build /p:Configuration=Debug /p:Platform=x86 

    - name: gui
      working-directory: ${{env.GITHUB_WORKSPACE}}module/gui      
      run: msbuild gui.sln /t:Build /p:Configuration=Debug /p:Platform=x86  
      
    - name: guiapp
      working-directory: ${{env.GITHUB_WORKSPACE}}module/guiapp      
      run: msbuild guiapp.sln /t:Build /p:Configuration=Debug /p:Platform=Win32  
      
    - name: login
      working-directory: ${{env.GITHUB_WORKSPACE}}module/login      
      run: msbuild login.sln /t:Build /p:Configuration=Debug /p:Platform=Win32 
      
    - name: make_image
      run: |      
        cd disk        
        copy bellona2-d.bin bellona2.bin
        ./belldisk.exe
        ./imagetool.exe gui.mod guiapp.mod jpeg.mod login.exe stdlib.mod wall.exe
        ./qemu-img.exe convert -O vmdk ./hdd.img ./hdd.vmdk
      
    - name: Upload a Build Artifact(bellona2)
      uses: actions/upload-artifact@v2.1.4
      with:
          name: bellona2
          path: disk


